# http 설정
server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  devtools:
    livereload:
      enabled: true
# 자동 재시작 사용 여부
    restart:
      enabled: true

# openvidu server 설정
openvidu:
  url: http://localhost:4443/
  secret: MY_SECRET