spring:
  datasource:
    url: hdbc:h2:tcp://localhost/~/webrtc
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: prod
server:
  port: 8080